name: Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: "deploy"
    runs-on: ubuntu-latest

    steps:
    - name: Build Binary
      run: ./scripts/buildprod

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Use gcloud CLI to get Info'
      run: gcloud info

    - name: 'Push Image to Artifact regsitry'
      run: gcloud builds submit --tag asia-south2-docker.pkg.dev/notely-405406/notely-ar-repo/notely:l2 .

