name: Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: "deploy"
    runs-on: ubuntu-latest

    steps:

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.20"
          
    - name: Check out code
      uses: actions/checkout@v3

    - name: Build Binary
      run: ./scripts/buildprod.sh

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Use gcloud CLI to get Info'
      run: gcloud info

    - name: 'Push image to Artifact regsitry'
      run: gcloud builds submit --tag asia-south2-docker.pkg.dev/notely-405406/notely-ar-repo/notely:latest .
    
    - name: 'Deploy to Cloud Run'
      run: >
        gcloud run deploy notely --image asia-south2-docker.pkg.dev/notely-405406/notely-ar-repo/notely:latest --region asia-south2 --allow-unauthenticated --project notely-405406 --max-instances=4
      


